### ISSUE TITLE
MacOS currently unsupported

### ISSUE THREAD

**Issue by rngkGit** [hlqGit/Yahtzee-in-Java#1]
Using macOS 14.3.1 and getting this error:
<img width="435" alt="Screenshot 2024-02-20 at 12 29 03" src="https://github.com/hlqGit/Yahtzee-in-Java/assets/64713406/80ebaaff-2fcf-4204-9bff-59c45d420602">
<img width="1247" alt="Screenshot 2024-02-20 at 12 42 21" src="https://github.com/hlqGit/Yahtzee-in-Java/assets/64713406/a756b3e1-57c2-4970-8bd2-599b131bc754">

**Comment by hlqGit** [comment]
I will work on finding a fix for this issue. This issue is strange because Java JARs are supposed to be cross platform.

**Comment by hlqGit** [comment]
I had to build it on VSCode using MacOS. I am not sure entirely why it gives out an error between different operating systems, so I will look into that. For now, I have uploaded the MacOS .jar file and Windows .jar file as a new release. Both of JAR files are built off of the same code, so the source code stays the same between the different JAR files.
